colors:
  # Default colors
  primary:
    background: '#000000'
    foreground: '#eeeeec'

  # Normal colors
  normal:
    black:   '#151515'
    red:     '#A12121'
    green:   '#0CAD5D'
    yellow:  '#F7CA88'
    blue:    '#0780B7'
    magenta: '#691C8B'
    cyan:    '#7CF8F8'
    white:   '#C5C8C6'

  # Bright colors
  bright:
    black:   '#151515'
    red:     '#A12121'
    green:   '#0CAD5D'
    yellow:  '#F7CA88'
    blue:    '#0780B7'
    magenta: '#691C8B'
    cyan:    '#7CF8F8'
    white:   '#C5C8C6'
